ServerTokens Prod
ServerSignature Off
PassEnv TOKEN
PassEnv WHITELIST
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html/src
    <Directory /var/www/html/src>
        Options -Indexes
        AllowOverride None
        Require all granted
        Header always set Access-Control-Allow-Origin "*"
        Header always set Content-Type "image/svg+xml" "expr=%{REQUEST_URI} =~ m#\.svg$#i"
        Header always set Content-Security-Policy "default-src 'none'; style-src 'unsafe-inline'; img-src data:;" "expr=%{REQUEST_URI} =~ m#\.svg$#i"
        Header always set Referrer-Policy "no-referrer-when-downgrade"
        Header always set X-Content-Type-Options "nosniff"
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
